### ISSUE TITLE
OBS Crashes if Controller is connected before startup

### ISSUE THREAD

**Issue by D34dlyK1ss** [univrsal/input-overlay#426]
**Describe the bug**
If I have my controller connected (USB) to the computer before opening OBS, when I try to open it, it crashes. This doesn't happen if I connect the controller after OBS starts

**To Reproduce**
Connect a controller
Start OBS

**Screenshots**
![image](https://github.com/user-attachments/assets/b7ea5716-9a14-4a35-889f-c821d9bc21bf)

**Additional information:**
- Plugin version 5.0.6
- Log: https://obsproject.com/logs/y9asBpSdR51RpY3N
- Crash Report: https://obsproject.com/logs/kYBDGWMPxw7O8bpM

**Comment by loicmagne** [comment]
Getting the same issue issue, on Ubuntu 24.04, OBS 31.0.0, input-overlay v5.0.6

The plugin seems to load correctly:

```bash
info: [input-overlay] Loading v5.0.6-HEAD (c99a526) build time 2024.10.24 17:24
warning: DEPRECATION: obs_frontend_get_global_config is deprecated. Read from global or user configuration explicitly instead.
info: [input-overlay] Initializing SDL2 for gamepad input (compile-time: 2.0.20, run-time:  2.30.0)
```

But then I get a segfault once all the plugins are loaded:

```bash
info: ------------------------------------------------
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.5) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_c3_00.6.HiFi__hw_Generic_1__sink.monitor' (default)
info: [Loaded global audio device]: 'Desktop Audio'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.5) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_c3_00.6.HiFi__hw_Generic_1__source' (default)
info: [Loaded global audio device]: 'Mic/Aux'
Segmentation fault (core dumped)
```

Only happens when my controller is already connected to my computer when obs starts

**Comment by univrsal** [comment]
Can you run `gdb obs -ex run` then once it crashes run `bt` and paste the back trace here? I want to check if it's the same function that's crashing.

**Comment by loicmagne** [comment]
Well it seems like I can't reproduce that crash anymore... My setup hasn't changed so I don't know what the issue was

**Comment by loicmagne** [comment]
Oh nvm, I managed the reproduce the crash, so for some reason it only happens when my gamepad is connected via bluetooth (and not usb). Here's the output of `gdb obs -ex run`/`bt`

```
Thread 37 "libobs: graphic" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff996006c0 (LWP 132832)]
Download failed: Invalid argument.  Continuing without source file ./nptl/./nptl/pthread_mutex_lock.c.
___pthread_mutex_lock (mutex=0x0) at ./nptl/pthread_mutex_lock.c:80
warning: 80	./nptl/pthread_mutex_lock.c: No such file or directory
(gdb) bt
#0  ___pthread_mutex_lock (mutex=0x0) at ./nptl/pthread_mutex_lock.c:80
#1  0x00007fffdf46c499 in ??? () at /usr/lib/x86_64-linux-gnu/obs-plugins/input-overlay.so
#2  0x00007ffff5572d1f in ??? () at /lib/x86_64-linux-gnu/libobs.so.30
#3  0x00007ffff55760b8 in ??? () at /lib/x86_64-linux-gnu/libobs.so.30
#4  0x00007ffff289ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#5  0x00007ffff2929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
